# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v2
    - uses: actions/labeler@v3
    - uses: actions/labeler@v4
    - uses: actions/labeler@v5
    - uses: actions/labeler@v6
    - uses: actions/labeler@v7
    - uses: actions/labeler@v8
    - uses: actions/labeler@v9
    - uses: actions/labeler@v10
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
     - uses: actions/labeler@v2
    - uses: actions/labeler@v3
    - uses: actions/labeler@v4
    - uses: actions/labeler@v5
    - uses: actions/labeler@v6
    - uses: actions/labeler@v7
    - uses: actions/labeler@v8
    - uses: actions/labeler@v9
    - uses: actions/labeler@v10
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
     - uses: actions/labeler@v2
    - uses: actions/labeler@v3
    - uses: actions/labeler@v4
    - uses: actions/labeler@v5
    - uses: actions/labeler@v6
    - uses: actions/labeler@v7
    - uses: actions/labeler@v8
    - uses: actions/labeler@v9
    - uses: actions/labeler@v10
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
     - uses: actions/labeler@v2
    - uses: actions/labeler@v3
    - uses: actions/labeler@v4
    - uses: actions/labeler@v5
    - uses: actions/labeler@v6
    - uses: actions/labeler@v7
    - uses: actions/labeler@v8
    - uses: actions/labeler@v9
    - uses: actions/labeler@v10
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
     - uses: actions/labeler@v2
    - uses: actions/labeler@v3
    - uses: actions/labeler@v4
    - uses: actions/labeler@v5
    - uses: actions/labeler@v6
    - uses: actions/labeler@v7
    - uses: actions/labeler@v8
    - uses: actions/labeler@v9
    - uses: actions/labeler@v10
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
     - uses: actions/labeler@v2
    - uses: actions/labeler@v3
    - uses: actions/labeler@v4
    - uses: actions/labeler@v5
    - uses: actions/labeler@v6
    - uses: actions/labeler@v7
    - uses: actions/labeler@v8
    - uses: actions/labeler@v9
    - uses: actions/labeler@v10
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
     - uses: actions/labeler@v2
    - uses: actions/labeler@v3
    - uses: actions/labeler@v4
    - uses: actions/labeler@v5
    - uses: actions/labeler@v6
    - uses: actions/labeler@v7
    - uses: actions/labeler@v8
    - uses: actions/labeler@v9
    - uses: actions/labeler@v10
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        repo-token1: "${{ secrets.GITHUB_test }}"
        repo-token2: "${{ secrets.GITHUB_test }}"
        
